# Generated by Django 4.2.20 on 2025-04-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="nickname",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
