# --- 1단계: React build ---
FROM node:18-alpine AS builder

WORKDIR /app

# 종속성과 코드 분리해서 레이어 캐시 활용
COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# --- 2단계: Nginx로 배포 ---
FROM nginx:stable-alpine

# (선택) Nginx 설정 덮어쓰기
COPY nginx.conf /etc/nginx/conf.d/default.conf

# 정적 파일 복사
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
