# Generated by Django 4.2.20 on 2025-04-08 22:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobdescriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdescription',
            name='title',
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 4, 8, 22, 57, 32, 199297, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='jds/'),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
