# Generated by Django 4.2.20 on 2025-04-14 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobdescriptions', '0002_remove_jobdescription_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('jd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='jobdescriptions.jobdescription')),
            ],
        ),
    ]
