# Generated by Django 4.2.20 on 2025-04-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('total', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_user',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company_user',
            name='is_reviewed',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
