# Generated by Django 4.2.20 on 2025-04-07 06:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobdescriptions', '0001_initial'),
        ('coverletters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('cover_letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='coverletters.coverletter')),
                ('job_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='jobdescriptions.jobdescription')),
            ],
        ),
    ]
