# Generated by Django 4.2.20 on 2025-04-08 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coverletters', '0002_coverletter_created_at_coverletter_is_reviewed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverLetterItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('cover_letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='coverletters.coverletter')),
            ],
        ),
    ]
