# Generated by Django 4.2.20 on 2025-03-27 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coverletters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matching_score', models.FloatField(help_text='JD와의 일치도 (0~1)')),
                ('grammar_score', models.FloatField(blank=True, null=True)),
                ('clarity_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cover_letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coverletters.coverletter')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField()),
                ('reason', models.CharField(help_text='추천 이유 또는 강조 키워드', max_length=255)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='feedback.feedback')),
            ],
        ),
    ]
